export { default as reqSong } from './reqSong';
// export { default as text } from "./text";
export { default as category } from './category';
export { default as detail } from './detail';
export { default as sign } from './sign';
export { default as chapter } from './chapter';
export { default as recommend } from './recommend';
export { default as hotSearch } from './hotSearch';
export { default as album } from './album';
export { default as reader } from './reader';
export { default as myList } from './myList';
export { default as relate } from './relate';
